### ISSUE TITLE
PyPi deployment not working

### ISSUE THREAD

**Issue by cdeline** [NREL/bifacialvf#21]
I'm trying to deploy 0.1.17 to PyPi  but I'm getting the following errors with twine check.  Any suggestions @mikofski ?

```
>>>python setup.py sdist
>>>twine check dist/*
```
```
Checking distribution dist\bifacialvf-0.1.7.tar.gz: warning: `long_description_content_type` missing.  defaulting to `text/x-rst`.
Failed
The project's long_description has invalid markup which will not be rendered on PyPI. The following syntax errors were detected:
line 81: Warning: Inline literal start-string without end-string.
```

**Comment by mikofski** [comment]
I think, but not sure, it might have something to do with the markdown in the readme. By default, PyPI expects ReStructured Text or `.rst` files, but if you are using the most current Twine, then you should be able to change the long description content type. See [including your readme in your package's metadata](https://packaging.python.org/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata).

**Comment by mikofski** [comment]
So it will work for wheels now, but not for the src-dist tarball.

    $ twine check dist/*
    Checking distribution dist/bifacialvf-0.1.7-py3-none-any.whl: Passed
    Checking distribution dist/bifacialvf-0.1.7.tar.gz: Failed
    The project's long_description has invalid markup which will not be rendered on PyPI. The following syntax errors were detected:
    line 83: Warning: Inline literal start-string without end-string.

There's a [bug in Twine that keeps it from reading the correct content type](https://github.com/pypa/twine/issues/454), also evidently twine also requires `readme_renderer[md]` to parse the long description. And even then, it still says there's an error on line 83. Looking into this now, sometimes sneaky bad bytes sneak into text during copy and paste :(

**Comment by mikofski** [comment]
@cdeline
- it was the [triple-backtick notation](../pull/22/files#diff-04c6e90faac2675aa89e2176d2eec7d8L43) used by GitHub flavored markdown that twine objected to
- and [the content-type issue with twine-1.13](https://github.com/pypa/twine/issues/454),
- so downgrade to [twine-1.12.1](https://pypi.org/project/twine/1.12.1/)
- and install [readme_renderer[md]](https://pypi.org/project/readme_renderer/)

      pip install twine==1.12.1 readme_renderer[md]

and you should be good to go
