### ISSUE TITLE
Errors with pvlib and importing .vf

### ISSUE THREAD

**Issue by bmcote** [NREL/bifacialvf#29]
Hello,

Below are a couple of errors I encounted while running bifacialvf and how I have alleviated them.

When initially running bifacialvf.simulate I got an error on line 95. I was able to resolve this by replacing (myTMY3,meta) = pvlib.tmy.readtmy3(TMYtoread) with (myTMY3,meta) = pvlib.iotools.read_tmy3(TMYtoread).

I was then getting the following error on line 30 when trying to import bifacialvf:
from .vf import getBackSurfaceIrradiances, getFrontSurfaceIrradiances, getGroundShadeFactors
ImportError: attempted relative import with no known parent package

I resolved this error by removing the periods in front of vf, sun, and readepw on lines 30-34 in bifacialvf. and line 14 of vf.

I believe these are bugs that need to be patched, but please let me know if it was just user error as I am new to python.

**Comment by cdeline** [comment]
The first is a pvlib error - an updated version of pvlib uses a different file IO convention.  The second is an absolute import error that I believe  is new with Python 3.8.  Similar to #32 .

**Comment by cdeline** [comment]
Fixed in development.
